### ISSUE TITLE
Todo for pred_ints

### ISSUE THREAD

**Issue by GrigoriJasnovidov** [aimclub/FEDOT#1165]
- [ ] Work with copies of last generation and final choice in get_last_generations: https://github.com/aimclub/FEDOT/blob/master/fedot/core/pipelines/prediction_intervals/utils.py
- [x] Work with possible options for mutations and data operations: https://github.com/aimclub/FEDOT/blob/master/fedot/core/pipelines/prediction_intervals/params.py
- [ ] Argument mutation_operations is a list of possible mutations and data operations for ts. Excluded mutations / data operations cause errors during fitting.
- [ ] Move get_distance_between to golem in https://github.com/aimclub/FEDOT/blob/master/fedot/core/pipelines/prediction_intervals/graph_distance.py . The expantion of function get_distance_between here allows us to compare just graphs without internal node parameters. 
- [ ] Fix unit tests that are disabled.
